# Generated by Django 3.2.13 on 2022-06-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('code', models.TextField(blank=True, db_column='Code', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('continent', models.TextField(blank=True, null=True)),
                ('langoff_1', models.TextField(blank=True, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('lon', models.TextField(blank=True, null=True)),
                ('colonizer1', models.TextField(blank=True, null=True)),
                ('religion', models.TextField(blank=True, db_column='Religion', null=True)),
                ('immigrants', models.TextField(blank=True, db_column='Immigrants', null=True)),
                ('country_border_code', models.TextField(blank=True, null=True)),
                ('utc_offset', models.TextField(blank=True, db_column='UTC_offset', null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'home_features',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ISO',
            fields=[
                ('code', models.TextField(blank=True, db_column='Code', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'home_iso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeanScores',
            fields=[
                ('from_country', models.TextField(blank=True, db_column='From country_iso2', null=True)),
                ('to_country', models.TextField(blank=True, db_column='To country_iso2', null=True)),
                ('points', models.TextField(blank=True, db_column='Points', null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'home_meanscores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeanScoresByYear',
            fields=[
                ('year', models.TextField(blank=True, db_column='Year', null=True)),
                ('to_country', models.TextField(blank=True, db_column='To country_iso2', null=True)),
                ('points', models.TextField(blank=True, db_column='Points', null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'home_meanscoresbyyear',
                'managed': False,
            },
        ),
    ]
