# Generated by Django 3.2.13 on 2022-06-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_juty_tele'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuRy',
            fields=[
                ('from_country', models.TextField(blank=True, null=True)),
                ('to_country', models.TextField(blank=True, null=True)),
                ('jury_or_voting', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('voted', models.TextField(blank=True, null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'home_juryvoting',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Juty',
        ),
    ]
